

@baseUrl = http://localhost:8089
@contentType = application/json

### 1.search all
GET  {{baseUrl}}/blog


### 2.search by keyword
GET  {{baseUrl}}/search
        ?keyword=keyword


### 3.generate code
POST  {{baseUrl}}/generator
Content-Type: {{contentType}}

{
    "dbConnectionProperty": {
        "url": "localhost:3306/boot-admin",
        "username": "root",
        "password": "root"
    },
    "genConfig": {
        "author": "aa",
        "packageName": "aa",
        "moduleName": "aa",
        "tableName": "sec_menu"
    }
}