server:
  port: 8088
  servlet:
    context-path: /

# rabbitmq配置
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true   # 开启发送确认
    publisher-returns: true    # 开启发送失败退回
    listener:
      simple:
        acknowledge-mode: manual      # 手动ack
        concurrency: 5
        max-concurrency: 10
      direct:
        acknowledge-mode: manual      # 手动ack
