server:
  port: 8088
  servlet:
    context-path: /

spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-boot-sample?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

  # 配置jpa
  jpa:
    database: mysql       # 数据库类型
    show-sql: true        # 打印sql语句
    hibernate:
      ddl-auto: update    # 加载 Hibernate时， 自动更新数据库结构

  # 配置redis
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 500ms
    lettuce:
      pool:
        minIdle: 0
        maxIdle: 10
        maxWait: 10000
        max-active: 10
