#### 索引映射管理
@baseUrl = http://localhost:9200
@contentType = application/json

#### API 基本格式：http://<ip>:<port>/<索引>/<类型>/<文档 id>


############################
##### 一、增加映射
############################

### 1.创建索引时指定 mapping
PUT  {{baseUrl}}/user
Content-Type: {{contentType}}

{
    "mappings": {
        "properties": {
            "id":{
                "type": "integer"
            },
            "name": {
                "type": "keyword"
            },
            "country": {
                "type": "keyword"
            },
            "birthday": {
                "type": "date",
                "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
            },
            "age": {
                "type": "integer"
            },
            "remark":{
                "type": "text"
            }
        }
    }
}


### 2.向已经存在的索引中添加 mapping
PUT  {{baseUrl}}/user/_mapping
Content-Type: {{contentType}}

{
    "properties": {
        "email":{
            "type": "keyword"
        } 
    }
}


############################
##### 二、获取映射
############################

### 1.获取映射
GET  {{baseUrl}}/user/_mapping

### 1.获取字段映射
GET  {{baseUrl}}/user/_mapping/field/email